<?php /* @var $this Xcom_Xfabric_Block_Adminhtml_System_Config_Form_Fieldset_Element_Button */ ?>
<button type="button" <?php echo $this->getId(); ?> name="<?php echo $this->getName(); ?>" style="<?php echo $this->getStyle();?>" class="<?php echo $this->getClass(); ?>" onclick="<?php echo $this->getOnclick(); ?>" <?php echo $this->getDisabled() ? 'disabled="disabled"' : ''; ?>>
    <span><?php echo $this->escapeHtml($this->getLabel()); ?></span>
</button>
